proxy:
  base-url: ${base_url:http://localhost}:${base_port:8080}
  endpoint: ${endpoint:/api/main-endpoint}

server:
  port: ${server-port:8081}

kafka-producer:
  enable: ${enable_kafka_proxy:true}
  topic-name: ${topic_name:REST.KAFKA.PROXY.TOPIC}
  bootstrap-servers: ${kafka_bootstrap_servers:localhost:9092}

kafka-message-mapper:
  enable: ${enable_kafka_message_mapper:true}
  rules-file-name: rest-server-mapper.jslt