proxy:
  base-url: ${base_url:http://localhost}:${base_port:8080}
  endpoint: ${endpoint:/api/main-endpoint}

server:
  port: ${server-port:8081}

kafka-producer:
  enable: ${kafka_proxy_enable:true}
  topic-name: ${topic_name:REST.KAFKA.PROXY.TOPIC}
  bootstrap-servers: ${kafka_bootstrap_servers:localhost:9092}
